//
//  ManagerFactory.swift
//  FootballRealm
//
//  Created by Kevin Zakszewski on 4/17/17.
//  Copyright © 2017 Kevin Zakszewski. All rights reserved.
//

import UIKit
import RealmSwift

class ManagerFactory {
    
    /*
     // Only override drawRect: if you perform custom drawing.
     // An empty implementation adversely affects performance during animation.
     override func drawRect(rect: CGRect) {
     // Drawing code
     }
     */
    
    static let sharedInstance = ManagerFactory()
    private init() {} //This prevents others from using the default '()' initializer for this class.
    
    
    func generateManager(minVal: Float)->Manager{
        let length = UInt32 (self.surnames.count)
        let rand = Int(arc4random_uniform(length))
        let coaching = Float(arc4random_uniform(50)) + minVal
        let tactical = Float(arc4random_uniform(50)) + minVal
        let transfer = Float(arc4random_uniform(50)) + minVal
        let manManagement = Float(arc4random_uniform(50)) + minVal

        let firstName = (self.randomStringWithLength(1) as String) + "."
        let surname = self.surnames[rand]
        let manager = Manager(name: firstName, surname: surname, coaching: coaching, tactical: tactical, transfer: transfer, manManagement: manManagement)
        return manager
    }
    
    //
    func randomStringWithLength (len : Int) -> NSString {
        
        let letters : NSString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        
        let randomString : NSMutableString = NSMutableString(capacity: len)
        
        for (var i=0; i < len; i++){
            let length = UInt32 (letters.length)
            var rand = arc4random_uniform(length)
            randomString.appendFormat("%C", letters.characterAtIndex(Int(rand)))
        }
        
        return randomString
    }
    
    
    
    var surnames : [String] = [
        "ABERNETHY",
        "ADAM",
        "ADCOCK",
        "ALDRIDGE",
        "ALLAN",
        "ANDREWS",
        "ARESOME",
        "ARNOLD",
        "BAKER",
        "BARBER",
        "BARLOW",
        "BARNET",
        "BELL",
        "BENTON",
        "BIRCH",
        "BLACKAMORE",
        "BLAIKIE",
        "BLANCHFLOWER",
        "BOELL",
        "BOOTH",
        "BOULTER",
        "BOUSAR",
        "BOWES",
        "BOWSER",
        "BOYDEN",
        "BRADFIELD",
        "BRANDY",
        "BREMNER",
        "BRIDE",
        "BROCKE",
        "BROCKIE",
        "BROOKE",
        "BROOMFIELD",
        "BROWN",
        "BROWNFIELD",
        "BRUER",
        "BUIE",
        "BULL",
        "BUSHELL",
        "CAKEBREAD",
        "CAMERON",
        "CAMPBELL",
        "CANNE",
        "CHALMERS",
        "CHAMBERLANE",
        "CHAMBERS",
        "CHARLES",
        "CHISHOLM",
        "CHISSET",
        "CHRISTIE",
        "CLARKE",
        "CLERK",
        "CLOSE",
        "COCKEN",
        "COOKE",
        "COPELAND",
        "CORKEN",
        "COUDAN",
        "COUPLAND",
        "COVERDALE",
        "COWDEN",
        "COWPER",
        "CRANSTON",
        "CRICHTON",
        "CRUICKSHANK",
        "DAKIN",
        "DAKION",
        "DALLACHIE",
        "DAMMANN",
        "DAVIDSON",
        "DELL",
        "DELPH",
        "DINGWALL",
        "DOUBLEDAY",
        "DOUBLEDEW",
        "DOUGLAS",
        "DRUMMOND",
        "DUCKE",
        "DUFF",
        "DUKE",
        "DUNCAN",
        "EDMONDSTONE",
        "EGGE",
        "ELDER",
        "ELLIS",
        "ELPHINSTONE",
        "ENGLEDEW",
        "ERSKINE",
        "EVERET",
        "FAIRLEY",
        "FEAKE",
        "FINDLAY",
        "FISHER",
        "FISKE",
        "FLEMING",
        "FLUNDERS",
        "FORBES",
        "FORBES-HOOD",
        "FORSYTH",
        "FRAMINGHAM",
        "FRIER",
        "GAIRDNE",
        "GARBUT",
        "GARMAN",
        "GAVENS",
        "GEDDES",
        "GERRARD",
        "GIBSON",
        "GILL",
        "GORDON",
        "GRAHAM",
        "GRANT",
        "GRINLAW",
        "HAENCKE",
        "HALL",
        "HAMILTON",
        "HANNUM",
        "HANSCOMBE",
        "HARDEN",
        "HARDER",
        "HARDING",
        "HARLAND",
        "HARWOOD",
        "HASS",
        "HAY",
        "HENRIE",
        "HENRY",
        "HEPBURN",
        "HILLIARD",
        "HILLS",
        "HINGST",
        "HIRD",
        "HODGSON",
        "HOLLINGWORTH",
        "HOLLOWAY",
        "HOOD",
        "HOOKES",
        "HORN",
        "HOWLET",
        "HUET",
        "HUME",
        "INGLEDEW",
        "INNES",
        "IRONSYD",
        "JACKSON",
        "JENNINGS",
        "JOHNSTONE",
        "JONES",
        "JUNGE",
        "KEITH",
        "KENNEDY",
        "KENT",
        "KER",
        "KID",
        "KINNIE",
        "KINNIS",
        "LADIKEN",
        "LAUREN",
        "LAWRENCE",
        "LEAD",
        "LEES",
        "LEIGHBODY",
        "LIGHTBODY",
        "LIVINGSTON",
        "LODGE",
        "LORRAIN",
        "LUMSDEN",
        "MACKENZIE",
        "MACKINTOSH",
        "MCCARMICK",
        "MCCLURG",
        "MCCOLM",
        "MCCOMB",
        "MCCULLOCH",
        "MCGAA",
        "MCGUFFOG",
        "MCINTOSH",
        "MCKINTOSH",
        "MCLURG",
        "MCMASTER",
        "MAIR",
        "MAITLAND",
        "MAN",
        "MANSFIELD",
        "MAPLETON",
        "MARTINE",
        "MATHESON",
        "MAYES",
        "MEIN",
        "MEINDERS",
        "MEINERD",
        "MEYFART",
        "MEYFORT",
        "MEYVERT",
        "MILLS",
        "MILNE",
        "MORDISON",
        "MORITZ",
        "MORRISON",
        "MURDISTON",
        "MURRAY",
        "NICHOLS",
        "NOBLE",
        "OGILVIE",
        "OGILVY",
        "PALLET",
        "PARLETT",
        "PATERSON",
        "PATRICKE",
        "PECK",
        "PHERSON",
        "PIRIE",
        "PLAMBECK",
        "PORTER",
        "PRATT",
        "PRESSED",
        "PRESSICK",
        "PRIOR",
        "PRISSICK",
        "RAITT",
        "RAW",
        "RAYMENT",
        "REDWYNE",
        "REID",
        "REIDFORD",
        "REIDFURD",
        "RICKET",
        "RIDER",
        "RIGG",
        "ROBERSON",
        "ROWE",
        "RUSSEL",
        "SANDILANDS",
        "SANDISON",
        "SCHEEL",
        "SCHLUETER",
        "SCHNOOR",
        "SCOTT",
        "SEAMAN",
        "SECKER",
        "SETON",
        "SHADBOLT",
        "SHAND",
        "SHAW",
        "SHIELL",
        "SHIMEN",
        "SHIMMEN",
        "SHIMMING",
        "SHORT",
        "SHOTBOLT",
        "SIEVERS",
        "SIM",
        "SKEGG",
        "SLUETERS",
        "SMAIL",
        "SMITH",
        "SNAWDON",
        "STEINSON",
        "STEPHEN",
        "STEPHENSON",
        "STEVEN",
        "STEVENSON",
        "STEVINSON",
        "STEWART",
        "STOKES",
        "STUART",
        "SUMNER",
        "SUMPTER",
        "SUTHERLAND",
        "TAIT",
        "TAYLOR",
        "THOMSON",
        "TICKELL",
        "TOLLER",
        "TOSH",
        "TURNER",
        "UNCKLE",
        "URQUHART",
        "USHER",
        "VINCENT",
        "VOLMERS",
        "VOSS",
        "WALKER",
        "WARD",
        "WARMAN",
        "WARREN",
        "WAUGH",
        "WEBB",
        "WEBSTER",
        "WEIR",
        "WELD",
        "WEST",
        "WHITE",
        "WIEBENSOHN",
        "WILLIAMS",
        "WILSON",
        "WOERGEL",
        "WOERPEL",
        "WOOD",
        "WREN",
        "WRIGHT"
    ]
    
    
}
